export const CarouselData = [
    {
        _id: 'adobe',
        subject : 'ADOBE',
        img : '../../../images/Adobe-logo.png',
        first : 'rose',
        second : 'bella',
        thrid : 'lily',
        firstrank : '#',
        secondrank : '#',
        thridrank : '#'
    },
    {
        _id: 'ai',
        subject : 'ARTIFICAL INTELLIGENCE',
        img : '../../../images/Adobe-logo.png',
        // img : require('./images/ai-logo.png'),
        first : 'rose',
        second : 'bella',
        thrid : 'lily',
        firstrank : '#',
        secondrank : '#',
        thridrank : '#'
    },
    // {
    //     _id: 'angular',
    //     subject : 'ANGULAR',
    //     img : require('../../../images/Adobe-logo.png'),
    //     // img : require('./images/angular-logo.png'),
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     _id: 'autocad',
    //     subject : 'AUTOCAD',
    //     img : require('../../../images/Adobe-logo.png'),
    //     // img : require('./images/autocad-logo.png'),
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     _id: 'aws',
    //     img : require('../../../images/Adobe-logo.png'),
    //     // img : require('./images/aws-logo.png'),
    //     subject : 'AWS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     _id: 'azure',
    //     img : require('../../../images/Adobe-logo.png'),
    //     // img : require('./images/azure-logo.png'),
    //     subject : 'AZURE',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     _id: 'cpp',
    //     img : require('../../../images/Adobe-logo.png'),
    //     // img : require('./images/c++-logo.png'),
    //     subject : 'C++ PROGRAMMING',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     _id: 'c',
    //     img : require('../../../images/Adobe-logo.png'),
    //     // img : require('./images/c-logo.png'),
    //     subject : 'C PROGRAMMING',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/cloudcomputing-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'CLOUD COMPUTING',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/cshrap-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'C# PROGRAMMING',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/css-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'CSS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/deeplearning-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'DEEP LEARNING',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/digitalmarketing-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'DIGITAL MARKETING ',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/django-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'DJANGO',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/docker-Logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'DOCKER',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/eclipse-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'ECLIPSE',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/express-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'EXPRESS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/fastapi-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'FASTAPI',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/flask-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'FLASK',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/flutter-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'FLUTTER',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/git-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'GIT',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/Go-Logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'GO',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/hadoop-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'HADOOP',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/html-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'HTML',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/java-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'JAVA',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/javascript-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'JAVASCRIPT',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/jquery-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'JQUERY',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/json-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'JSON',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/Kotlin-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'KOTLIN',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/linux-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'LINUX',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/machinelearning-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'MACHINE LEARNING',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/MATLAB-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'MATLAB',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {			
    //     // img : require('./images/mongodb-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'MONGO-DB',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/mysql-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'MYSQL',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/net-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'NET',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/next-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'NEXT.JS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/node-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'NODE.JS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/php-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'PHP',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/postman-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'POSTMAN',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/Python-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'PYTHON',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/R-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'R',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/react-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'REACT',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/redux-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'REDUX',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/restapi-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'RESTAPI',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/ruby-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'RUBY',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/rubyonrails-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'RUBY ON RAILS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/rust-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'RUST',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/seo-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'SEO',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/spark-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'SPARK',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/sql-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'SQL',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/swift-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'SWIFT',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/tailwind-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'TAILWIND-CSS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/Typescript-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'TYPESCRIPT',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/vue-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'VUE',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/WordPress-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'WORDPRESS',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
    // {
    //     // img : require('./images/xml-logo.png'),
    //     img : require('../../../images/Adobe-logo.png'),
    //     subject : 'XML',
    //     first : 'rose',
    //     second : 'bella',
    //     thrid : 'lily',
    //     firstrank : '#',
    //     secondrank : '#',
    //     thridrank : '#'
    // },
]
